language: python
python:
  - "2.6"
  - "2.7"
env:
  - DJANGO=1.2.7
  - DJANGO=1.3.1
  - DJANGO=1.4
  - DJANGO=1.5.5
  - DJANGO=1.6.1
before_install:
  - sudo apt-get install libjpeg-dev
  - sudo ln -s /usr/lib/x86_64-linux-gnu/libjpeg.so /usr/lib
install:
  - pip install Django==$DJANGO
  - pip install -r tests/requirements.txt
script:
  - python tests/manage.py test